---
language: python
python: "2.7"

install:
  - pip install ansible
  - pip install pep8
  - pip install -r requirements.txt

script:
  - cd test
  - ansible-playbook test.yml -e ansible_python_interpreter=/home/travis/virtualenv/python2.7/bin/python
  - cd ..
  - pep8 library
